Unreviewed. Fix debug build error since r196847
Fix gcc build warning appeared as below
by removing BASSERT(refCount <= maxRefCount).
error: comparison is always true due to limited range of data type
[-Werror=type-limits]

* bmalloc/SmallLine.h:
(bmalloc::SmallLine::ref): Deleted.

Identifier: 172598@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@196856 268f45cc-cd09-0410-ab3c-d52691b4dbfc