Unreviewed build fix. WebCore has a weak symbol.
WebCore has a weak external symbol in it. A common cause of weak external
symbols is when an inline function is listed in the linker export file.
ERROR: symbol __ZNK7WebCore4Page25expectsWheelEventTriggersEv

* page/Page.cpp:
(WebCore::Page::expectsWheelEventTriggers):
* page/Page.h:
(WebCore::Page::expectsWheelEventTriggers): Deleted.

Identifier: 162454@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@183616 268f45cc-cd09-0410-ab3c-d52691b4dbfc