Uncaught Exception: TypeError: this._textEditor.toggleUnexecutedCodeHighlights().then is not a function https://bugs.webkit.org/show_bug.cgi?id=181912 <rdar://problem/36700022>
Reviewed by Matt Baker.

The uncaught exception was caused by returning `false` instead of a promise object.
This patch only fixes the exception. Further enhancements should be done in <https://webkit.org/b/183887>.

* UserInterface/Views/SourceCodeTextEditor.js:
(WI.SourceCodeTextEditor.prototype.toggleTypeAnnotations):
(WI.SourceCodeTextEditor.prototype.toggleUnexecutedCodeHighlights):


Identifier: 199509@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@229874 268f45cc-cd09-0410-ab3c-d52691b4dbfc