Enable IPC sending and receiving non-default-constructible types https://bugs.webkit.org/show_bug.cgi?id=196132 <rdar://problem/49229221>
Unreviewed build fix for WinCairo port.

error C2440: '=': cannot convert from 'int' to 'HANDLE'

* Platform/win/SharedMemoryWin.cpp:
(WebKit::SharedMemory::Handle::Handle): std::exchange HANDLE with nullptr, not 0.
(WebKit::SharedMemory::Handle::operator=): Ditto.

Identifier: 210534@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@243479 268f45cc-cd09-0410-ab3c-d52691b4dbfc