Fix build after r165472
Fixes the following build failure:

    WebCore/rendering/shapes/Shape.cpp:97:20: error: unused function 'ensureRadiiDoNotOverlap' [-Werror,-Wunused-function]
    static inline void ensureRadiiDoNotOverlap(FloatRect& bounds, FloatSize& radii)
                       ^
    1 error generated.

* rendering/shapes/Shape.cpp:
(ensureRadiiDoNotOverlap): Remove unused function.

Identifier: 148085@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@165474 268f45cc-cd09-0410-ab3c-d52691b4dbfc