[WinCairo] REGRESSION(r265408): Unreviewed layout test script fix https://bugs.webkit.org/show_bug.cgi?id=215292 <rdar://problem/66698141>
os.getuid() is available only for Unix.

> AttributeError: 'module' object has no attribute 'getuid'

* Scripts/webkitpy/__init__.py: Don't use os.getuid() unless sys.platform == 'darwin'.

Identifier: 228087@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@265409 268f45cc-cd09-0410-ab3c-d52691b4dbfc