[EFL] WebKit DRT and WTR fail to build due to undefined reference to WTF::MD5::* https://bugs.webkit.org/show_bug.cgi?id=90868
Unreviewed EFL build fix.

Correct CMake configuration to have EFL's DRT and WebKitTestRunner link
WTF library. This is needed to resolve undefined reference to WTF::MD5::*.

Patch by Christophe Dumez <christophe.dumez@intel.com> on 2012-07-10

* DumpRenderTree/efl/CMakeLists.txt:
* WebKitTestRunner/PlatformEfl.cmake:

Identifier: 108704@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@122213 268f45cc-cd09-0410-ab3c-d52691b4dbfc