REGRESSION (r238749): run-api-tests dies with AttributeError: 'IOSSimulatorPort' object has no attribute 'DEFAULT_DEVICE_CLASS' https://bugs.webkit.org/show_bug.cgi?id=192257 <rdar://problem/46384671>
Reviewed by Stephanie Lewis.

Follow-up fix for r238749.

* Scripts/webkitpy/api_tests/manager.py:
(Manager._initialize_devices): Use DEFAULT_DEVICE_TYPE instead of DEFAULT_DEVICE_CLASS.


Identifier: 206907@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@238763 268f45cc-cd09-0410-ab3c-d52691b4dbfc