[Win Debug] Unreviewed build fix
> JavaScriptCore/runtime/JSArrayBufferView.cpp(51): error C2660: 'Gigacage::isEnabled': function does not take 0 arguments

* wtf/Gigacage.h:
(Gigacage::isEnabled): Added isEnabled taking no argument which was adeed to bmalloc in r249556 (Bug 201521).

Identifier: 227757@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@265057 268f45cc-cd09-0410-ab3c-d52691b4dbfc