REGRESSION (r176137): iOS build broke after moving DataDetectors scanning code to WebCore
This regressed with the following commit:

    Move DataDetectors scanning code to WebCore
    https://bugs.webkit.org/show_bug.cgi?id=138731
    <rdar://problem/18877535>

Source/WebCore:

This fixes the following build failures:

    In file included from WebCore/editing/mac/DataDetection.mm:29:
    WebCore/platform/spi/mac/DataDetectorsSPI.h:66:11: error: unknown type name 'NSRect'
    @property NSRect highlightFrame;
              ^
    WebCore/editing/mac/DataDetection.mm:42:28: error: use of undeclared identifier 'DataDetection'
    RetainPtr<DDActionContext> DataDetection::detectItemAroundHitTestResult(const HitTestResult& hitTestResult, FloatRect& detectedDataBoundingBox, RefPtr<Range>& detectedDataRange)
                               ^
    2 errors generated.

* WebCore.exp.in:
(DataDetection::detectItemAroundHitTestResult): Move symbol from
shared section to Mac-only section.
* editing/mac/DataDetection.mm: Add PLATFORM(MAC) check around
the entire implementation since it it unused on iOS.
* platform/spi/mac/DataDetectorsSPI.h: Expand PLATFORM(MAC)
check around DDActionContext class declarations.

Source/WebKit2:

* Shared/mac/ActionMenuHitTestResult.mm: Add PLATFORM(MAC) check
around the entire implementation since it it unused on iOS.

Identifier: 156614@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@176156 268f45cc-cd09-0410-ab3c-d52691b4dbfc