BUILD FIX: Platform.h:1212:22: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
This fixes the following build error introduced in r140366 for
Bug 107098:

    Platform.h:1212:22: error: '__MAC_OS_X_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]
    #if PLATFORM(MAC) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1080 && !PLATFORM(IOS)
                         ^
    1 error generated.

* wtf/Platform.h: Check !PLATFORM(IOS) first so that iOS builds
do not try to evaluate __MAC_OS_X_VERSION_MIN_REQUIRED.

Identifier: 126297@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@140988 268f45cc-cd09-0410-ab3c-d52691b4dbfc