Unreviewed build fix for chromium/mac & clang.
Fix the macro redefinition error by r94927, because chromium set
ENABLE_JSC_MULTIPLE_THREADS=0 in WebKit/chromium/features.gypi and
it is not PLATFORM(QT).
 ../../JavaScriptCore/wtf/Platform.h:512:9: error: 'ENABLE_JSC_MULTIPLE_THREADS' macro redefined [-Werror]
 #define ENABLE_JSC_MULTIPLE_THREADS 1
 <command line>:43:9: note: previous definition is here
 #define ENABLE_JSC_MULTIPLE_THREADS 0
 1 error generated.

* wtf/Platform.h:

Identifier: 83825@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@94939 268f45cc-cd09-0410-ab3c-d52691b4dbfc