BUILD FIX (r146687): setDefaultMIMEType() is unused in ResourceHandleCFNet.cpp on iOS
Fixes the following build failure:

    Source/WebCore/platform/network/cf/ResourceHandleCFNet.cpp:98:13: error: unused function 'setDefaultMIMEType' [-Werror,-Wunused-function]
    static void setDefaultMIMEType(CFURLResponseRef response)
                ^
    1 error generated.

* platform/network/cf/ResourceHandleCFNet.cpp:
(WebCore::setDefaultMIMEType): Add #if !PLATFORM(MAC)/#endif
guard.

Identifier: 131487@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@146718 268f45cc-cd09-0410-ab3c-d52691b4dbfc