REGRESSION (r173988): Fix unused variable warning in PDFDocumentImage.cpp
Fixes the following build failure in release builds:

    WebCore/platform/graphics/cg/PDFDocumentImage.cpp:230:12: error: unused variable 'pageCount' [-Werror,-Wunused-variable]

* platform/graphics/cg/PDFDocumentImage.cpp:
(WebCore::PDFDocumentImage::computeBoundsForCurrentPage): Change
ASSERT() to call pageCount().

Identifier: 154968@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@174018 268f45cc-cd09-0410-ab3c-d52691b4dbfc