AttributeError: StatusServer instance has no attribute '_api_key' thrown when processing a patch https://bugs.webkit.org/show_bug.cgi?id=186852
Fixes an issue where StatusServer._api_key may not be defined. This issue manifests itself
in a Python AttributeError exception when an EWS bot tries to fetch the next patch to process.

Currently StatusServer._api_key is only defined when either the environment variable WEBKIT_STATUS_API_KEY
or the Git configuration key webkit.status_api_key has a non-empty value. Instead we should
always define StatusServer._api_key in the StatusServer constructor.

* Scripts/webkitpy/common/net/statusserver.py:
(StatusServer.__init__):

Identifier: 202124@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@233024 268f45cc-cd09-0410-ab3c-d52691b4dbfc