Build error: DNSSoup.cpp:30: fatal error: CString.h: No such file or directory https://bugs.webkit.org/show_bug.cgi?id=81093
Patch by Sudarsana Nagineni <sudarsana.nagineni@linux.intel.com> on 2012-03-14
Reviewed by Philippe Normand.

Fix build error introduced by r110669.

* platform/network/soup/DNSSoup.cpp:

Identifier: 98271@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@110697 268f45cc-cd09-0410-ab3c-d52691b4dbfc