[chromium] Unreviewed build fix on Linux clang.
../../third_party/WebKit/Source/WebKit/chromium/src/FrameLoaderClientImpl.cpp:1055:63: error:
C++98 requires an accessible copy constructor for class 'WebKit::WebCachedURLRequest' when binding
a reference to a temporary; was private [-Werror,-Wbind-to-temporary-copy]

* src/FrameLoaderClientImpl.cpp:
(WebKit::FrameLoaderClientImpl::dispatchWillRequestResource):

Identifier: 121524@main
git-svn-id: https://svn.webkit.org/repository/webkit/trunk@135877 268f45cc-cd09-0410-ab3c-d52691b4dbfc